# Generated by Django 5.2.11 on 2026-04-07 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0001_initial'),
        ('catalog', '0013_breakdown_description_breakdown_description_en_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VacuumBrandsAdminEntry',
        ),
        migrations.CreateModel(
            name='BrandCategoryAdminEntry',
            fields=[
            ],
            options={
                'verbose_name': 'Тип техники',
                'verbose_name_plural': 'Типы техники',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('catalog.category',),
        ),
    ]
