# Generated by Django 5.2.11 on 2026-03-22 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_name', models.CharField(max_length=100, unique=True)),
                ('name_ru', models.CharField(max_length=255)),
                ('name_ua', models.CharField(max_length=255)),
                ('name_en', models.CharField(max_length=255)),
                ('folder', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(blank=True, max_length=255, null=True)),
                ('description_ru', models.TextField(blank=True, null=True)),
                ('specs_ru', models.JSONField(default=dict)),
                ('name_ua', models.CharField(blank=True, max_length=255, null=True)),
                ('description_ua', models.TextField(blank=True, null=True)),
                ('specs_ua', models.JSONField(default=dict)),
                ('name_en', models.CharField(blank=True, max_length=255, null=True)),
                ('description_en', models.TextField(blank=True, null=True)),
                ('specs_en', models.JSONField(default=dict)),
                ('images', models.JSONField(default=list)),
                ('source_url', models.URLField(blank=True, max_length=500, null=True)),
                ('product_folder', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='catalog.category')),
            ],
        ),
    ]
