# Generated by Django 5.2.11 on 2026-03-31 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_vacuumbrand_category_scope'),
    ]

    operations = [
        migrations.CreateModel(
            name='Breakdown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Поломка')),
                ('possible_causes', models.TextField(verbose_name='Возможные причины')),
                ('what_to_check', models.TextField(verbose_name='Что проверить')),
                ('how_to_fix', models.TextField(verbose_name='Как исправить')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breakdowns', to='catalog.vacuumbrand', verbose_name='Бренд')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breakdowns', to='catalog.category', verbose_name='Тип техники')),
            ],
            options={
                'verbose_name': 'Поломка',
                'verbose_name_plural': 'Поломки',
                'ordering': ['category__name_ru', 'brand__name', 'title'],
            },
        ),
    ]
