# Generated by Django 5.2.11 on 2026-03-31 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_breakdown_fields_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='breakdown',
            name='how_to_fix_en',
            field=models.TextField(blank=True, default='', verbose_name='Как исправить (EN)'),
        ),
        migrations.AddField(
            model_name='breakdown',
            name='how_to_fix_ua',
            field=models.TextField(blank=True, default='', verbose_name='Как исправить (UA)'),
        ),
        migrations.AddField(
            model_name='breakdown',
            name='possible_causes_en',
            field=models.TextField(blank=True, default='', verbose_name='Возможные причины (EN)'),
        ),
        migrations.AddField(
            model_name='breakdown',
            name='possible_causes_ua',
            field=models.TextField(blank=True, default='', verbose_name='Возможные причины (UA)'),
        ),
        migrations.AddField(
            model_name='breakdown',
            name='title_en',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Поломка (EN)'),
        ),
        migrations.AddField(
            model_name='breakdown',
            name='title_ua',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Поломка (UA)'),
        ),
        migrations.AddField(
            model_name='breakdown',
            name='what_to_check_en',
            field=models.TextField(blank=True, default='', verbose_name='Что проверить (EN)'),
        ),
        migrations.AddField(
            model_name='breakdown',
            name='what_to_check_ua',
            field=models.TextField(blank=True, default='', verbose_name='Что проверить (UA)'),
        ),
        migrations.AlterField(
            model_name='breakdown',
            name='how_to_fix',
            field=models.TextField(blank=True, default='', verbose_name='Как исправить (RU)'),
        ),
        migrations.AlterField(
            model_name='breakdown',
            name='possible_causes',
            field=models.TextField(blank=True, default='', verbose_name='Возможные причины (RU)'),
        ),
        migrations.AlterField(
            model_name='breakdown',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Поломка (RU)'),
        ),
        migrations.AlterField(
            model_name='breakdown',
            name='what_to_check',
            field=models.TextField(blank=True, default='', verbose_name='Что проверить (RU)'),
        ),
        migrations.AlterField(
            model_name='breakdowngroup',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Группа поломок'),
        ),
    ]
