# Generated by Django 5.2.11 on 2026-03-31 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_breakdown_how_to_fix_en_breakdown_how_to_fix_ua_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='breakdown_groups',
            field=models.ManyToManyField(blank=True, related_name='products_multi', to='catalog.breakdowngroup', verbose_name='Дополнительные группы поломок'),
        ),
    ]
