# Generated by Django 5.2.11 on 2026-04-07 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_product_breakdown_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='breakdown',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Описание (RU)'),
        ),
        migrations.AddField(
            model_name='breakdown',
            name='description_en',
            field=models.TextField(blank=True, default='', verbose_name='Описание (EN)'),
        ),
        migrations.AddField(
            model_name='breakdown',
            name='description_ua',
            field=models.TextField(blank=True, default='', verbose_name='Описание (UA)'),
        ),
    ]
