# Generated by Django 5.2.11 on 2026-04-28 06:15

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_breakdown_description_breakdown_description_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата публикации')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('title_ru', models.CharField(max_length=255, verbose_name='Заголовок (RU)')),
                ('excerpt_ru', models.TextField(blank=True, default='', verbose_name='Краткое описание (RU)')),
                ('content_ru', models.TextField(verbose_name='Текст статьи (RU)')),
                ('title_ua', models.CharField(max_length=255, verbose_name='Заголовок (UA)')),
                ('excerpt_ua', models.TextField(blank=True, default='', verbose_name='Краткое описание (UA)')),
                ('content_ua', models.TextField(verbose_name='Текст статьи (UA)')),
                ('title_en', models.CharField(max_length=255, verbose_name='Заголовок (EN)')),
                ('excerpt_en', models.TextField(blank=True, default='', verbose_name='Краткое описание (EN)')),
                ('content_en', models.TextField(verbose_name='Текст статьи (EN)')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ArticleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='articles/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif'])], verbose_name='Изображение')),
                ('alt_ru', models.CharField(blank=True, default='', max_length=255, verbose_name='Alt (RU)')),
                ('alt_ua', models.CharField(blank=True, default='', max_length=255, verbose_name='Alt (UA)')),
                ('alt_en', models.CharField(blank=True, default='', max_length=255, verbose_name='Alt (EN)')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.article', verbose_name='Статья')),
            ],
            options={
                'verbose_name': 'Изображение статьи',
                'verbose_name_plural': 'Изображения статей',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
