# Generated by Django 5.2.11 on 2026-04-29 14:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_article_articleimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleimage',
            name='cloudflare_url',
            field=models.URLField(blank=True, default='', help_text='Пример: https://pub-...r2.dev/items/test/1.jpg', max_length=1000, verbose_name='Ссылка Cloudflare (R2)'),
        ),
        migrations.AlterField(
            model_name='articleimage',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='articles/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif'])], verbose_name='Изображение (legacy)'),
        ),
    ]
